# syntax = devthefuture/dockerfile-x
INCLUDE ./Dockerfile-builder

FROM node AS node

FROM debian:bookworm-slim

INCLUDE ./snippets/node

INCLUDE ./snippets/go

INCLUDE ./snippets/git

INCLUDE ./snippets/dart-sass

INCLUDE ./snippets/common

INCLUDE ./snippets/user
