# syntax = devthefuture/dockerfile-x
INCLUDE ./Dockerfile-builder

FROM node:alpine AS node

FROM alpine

INCLUDE ./snippets/node

INCLUDE ./snippets/dart-sass

INCLUDE ./snippets/common

INCLUDE ./snippets/user
