# syntax = edrevo/dockerfile-plus
INCLUDE+ ./Dockerfile-builder

FROM node:alpine AS node

FROM alpine:edge

INCLUDE+ ./snippets/node

INCLUDE+ ./snippets/go

INCLUDE+ ./snippets/git

INCLUDE+ ./snippets/dart-sass

INCLUDE+ ./snippets/common
