# syntax = edrevo/dockerfile-plus
INCLUDE+ ./Dockerfile-builder

FROM node:alpine as node

FROM alpine:edge

COPY --from=node /usr/lib /usr/lib
COPY --from=node /usr/local/lib /usr/local/lib
COPY --from=node /usr/local/include /usr/local/include
COPY --from=node /usr/local/bin /usr/local/bin

INCLUDE+ ./snippets/go

INCLUDE+ ./snippets/git

INCLUDE+ ./snippets/exts

INCLUDE+ ./snippets/common
