# syntax = devthefuture/dockerfile-x
INCLUDE ./snippets/builder

FROM alpine:edge

INCLUDE ./snippets/common

INCLUDE ./snippets/dart-sass

INCLUDE ./snippets/git

INCLUDE ./snippets/go

INCLUDE ./snippets/user
