# syntax = devthefuture/dockerfile-x
INCLUDE ./snippets/builder

FROM node:alpine AS node

FROM alpine:edge

INCLUDE ./snippets/node

INCLUDE ./snippets/go

INCLUDE ./snippets/git

INCLUDE ./snippets/dart-sass

INCLUDE ./snippets/common

INCLUDE ./snippets/user
